config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :books, :rentals
  devise_for :users, controllers: {sessions: 'users/sessions'}, :path_prefix => 'my'
  resources :users
  get 'static/home'

  root 'static#home'
end

app/models/rental.rb
# frozen_string_literal: true

class Rental < ApplicationRecord
  belongs_to :user

  # Using Activerecord scopes for filtering
  scope :filter_by_status, ->(status) { where active: status }
  scope :filter_by_checkout, lambda { |init_date, end_date|
                               where('checkout_date >= ? and checkout_date < ?', init_date, end_date)
                             }

  before_create :init_check_out_book

  after_destroy :revert_checkout

  # Initial setup
  def init_check_out_book
    self.active = true
    self.checkout_date = Time.now
    book = Book.find(book_id)
    book.toggle_check_out
    self.book_title = book.title
  end

  # When rental is done, reverts the book availability
  def finalize
    self.active = false
    self.checkin_date = Time.now
    Book.find(book_id).toggle_check_out
  end

  # On destroy reverts book's checkout status
  def revert_checkout
    Book.find(book_id).toggle_check_out
  end

  def book
    book_title
  end
end

app/controllers/rentals_controller.rb
# frozen_string_literal: true

class RentalsController < ApplicationController
  before_action :set_rental, only: [:show, :edit, :update, :destroy]
  before_action :book_checked_out, only: :create
  before_action :base_index_filtering, only: :index

  def index
    # Applies filter to collection of data depending on wich user is signed in
    @rentals = apply_filter(@rentals)

    @rentals = @rentals.page(params[:page])
  end

  def show
    @book = Book.find(@rental.book_id)
  end

  def new
    @rental = Rental.new
    @book_id = params[:format]
  end

  def create
    @rental = Rental.new(rental_params)

    if @rental.save
      redirect_to rental_url(@rental)
    else
      redirect_to root_path
    end
  end

  def edit; end

  def update
    @rental.finalize

    if @rental.save
      redirect_to rental_url(@rental)
    else
      redirect_to root_path
    end
  end

  def destroy
    redirect_to root_path if @rental.destroy
  end

  private

  def set_rental
    @rental = Rental.find(params[:id])
  end

  def rental_params
    params.require(:rental).permit(:book_id, :user_id)
  end

  def book_checked_out
    redirect_to root_path if Book.checked_out?(rental_params[:book_id])
  end

  # Simple filtering given the parameters that are passed to the controller
  def apply_filter(data)
    return data.filter_by_status(params[:status]) if params[:status].present?
    return data.filter_by_checkout(params[:checkout_date_init], params[:checkout_date_end]) if params[:checkout_date_end].present?

    data
  end

  # Logic necessary to only show normal users their rentals and admins all rentals
  def base_index_filtering
    @rentals = current_user.admin? ? Rental.all : current_user.rentals
  end
end

app/helpers/rentals_helper.rb
# frozen_string_literal: true

module RentalsHelper
end

app/views/rentals/_form.html.erb
<%= form_with(model: @rental) do |f| %>

<% if @rental.errors.any? %>
  <div class="alert alert-danger">
    <h2><%= pluralize(@rental.errors.count, "error") %> prohibited this rental from being saved:</h2>
    <ul>
      <% @rental.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

   <div class="input-group">
     <span class="input-group-addon"><%= f.label :user_id, "User #" %></span>
     <%= f.number_field :user_id, class:"form-control" %>
  </div>

   <div class="input-group">
     <span class="input-group-addon"><%= f.label :book_id, "Book #"  %></span>
    <%= f.number_field :book_id, value: @book_id , class:"form-control" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rentals/edit.html.erb
<h1>Edit rental</h1>
<%= render 'form' %>

<% content_for :right_pane do %>
  <%= button_to "Back", rental_path(@rental), class: "btn" , method: :get%>
<% end %>

app/views/rentals/index.html.erb
<h1>Rentals</h1>

<%= paginate @rentals %>
<div class="library">
<% @rentals.each do |rental|  %>
	<%= link_to(rental, class: "book-item") do%>
		<h2>Rental #<%= rental.id %>: <%= rental.book %></h2>
		<p><b>Checkout date:</b> <%= rental.checkout_date %></p>
		
		
	<% end %>
<% end %>

<% content_for :right_pane do %>

	<div class="filters">
	<h2> Filters:</h2>
		<%= form_with url: rentals_path, method: :get do |form| %>
		<h3>Filter by checkout date:</h3>
		  <div class="input-group">
			  <span class="input-group-addon"><%= form.label :checkout_date_init, "Start:" %></span>
			  <%= form.date_field :checkout_date_init, class:"form-control" %>
		  </div>

		  <div class="input-group">
			  <span class="input-group-addon"><%= form.label :checkout_date_end, "End:" %></span>
			  <%= form.date_field :checkout_date_end, class:"form-control" %>
		  </div>
		  <h3>Filter by status:</h3>
		  <div class="input-group">
			  <span class="input-group-addon"><%= form.radio_button :status, "true" %> </span>
			  <%= form.label :status, "Active", class:"form-control" %> 
		  </div>
		  <div class="input-group">
			  <span class="input-group-addon"><%= form.radio_button :status, "false" %></span>
			  <%= form.label :status, "Inactive", class:"form-control" %> 
		  </div>
	  	<%= form.submit "Filter", class:"btn" %>
	   <% end %>
	</div>

<% end %>

</div>

app/views/rentals/new.html.erb
<h1>New rental</h1>
<%= render 'form' %>

<% content_for :right_pane do %>
  <%= button_to "Back", book_path(@book_id), class: "btn" , method: :get unless @book_id.nil?%>
<% end %>

app/views/rentals/show.html.erb
<div class="title-show">
	<h1>Rental # <%= @rental.id %> </h1>
	<div>
	<% if @rental.active %>
		<span class="label label-success">Active</span>
	<% else %>
		<span class="label label-danger">Inactive</span>
	<% end %>		
	</div>
</div>

<div class="rental-dates">
	<div class="due-date due-date-start"><b>Check-out date:</b> </br> <%= @rental.checkout_date %></div>
	<div class="due-date"><b>Check-in date:</b> </br> <%= @rental.checkin_date %></div>
</div>

<div class="library">
	<h2>Book: </h2>
	<%= link_to(book_path(@book), class: "book-item") do%>
		<h2><%= @rental.book%> </h2>
		<p><b>Author:</b>	<%= @book.author %></p>
		<p><b>Caregory:</b> <%= @book.category %></p>
	<% end %>
</div>
<% content_for :right_pane do %>
	<% if current_user.admin? %>
		<%= button_to "Finalize rental", rental_path(@rental), method: :patch%>
		<%= button_to "Destroy rental", rental_path(@rental), method: :delete%>
	<% else %>
		<%= button_to "Back", rentals_path, method: :get%>
	<% end %>
<% end %>