config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :books, :rentals
  devise_for :users, controllers: {sessions: 'users/sessions'}, :path_prefix => 'my'
  resources :users
  get 'static/home'

  root 'static#home'
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  validates_presence_of :title, :author, :category
  validates_uniqueness_of :title

  # Using Activerecord scopes for filtering
  scope :filter_by_title, ->(title) { where('title like ?', "%#{title}%") }
  scope :filter_by_author, ->(author) { where('author like ?', "%#{author}%") }
  scope :filter_by_category, ->(category) { where category: }
  scope :filter_by_status, ->(status) { where check_out: status }

  def self.checked_out?(id)
    Book.find(id).check_out
  end

  # Using a logic gate to toggle the checkout status when needed
  def toggle_check_out
    self.check_out ^= true
    save
  end
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :only_admin, only: [:new, :edit]
  skip_before_action :authorized, only: :index

  def index
    @books = Book.page(params[:page])

    # Simplifying the many filter calls, its called on demand now

    filtering_params(params).each do |key, value|
      @books = @books.public_send("filter_by_#{key}", value) if value.present?
    end
  end

  def show; end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to book_url(@book)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @book.update(book_params)
      redirect_to book_url(@book)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @book.destroy && current_user.admin?
      redirect_to root_path
    else
      render :show, flash: {notice: "Server error: can't delete book"}
    end
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:author, :title, :category, :check_out)
  end

  def only_admin
    redirect_to root_path unless current_user.admin?
  end

  # Sets up all the filters that can be applied and its parameter names
  def filtering_params(params)
    params.slice(:title, :author, :category, :status)
  end
end

app/helpers/books_helper.rb
# frozen_string_literal: true

module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with(model: @book, local: true) do |f| %>

<% if @book.errors.any? %>
  <div class="alert alert-danger">
    <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <div class="input-group">
    <span class="input-group-addon"><%= f.label :title %></span>
    <%= f.text_field :title, class:"form-control"%>
  </div>

  <div class="input-group">
    <span class="input-group-addon"><%= f.label :author %></span>
    <%= f.text_field :author, class:"form-control" %>
  </div>

  <div class="input-group">
    <span class="input-group-addon"><%= f.label :category %></span>
    <%= f.text_field :category, class:"form-control" %>
  </div>

  <div class="input-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing: <%= @book.title %></h1>
<%= render 'form'%>

<% content_for :right_pane do %>
  <%= button_to "Back", book_path(@book), class: "btn", method: :get%>
<% end %>

app/views/books/index.html.erb
<h1>Library</h1>

<%= paginate @books %>
<div class="library">
<% @books.each do |book|  %>
	<%= link_to(book, class: "book-item active-#{book.check_out}") do%>
		<h2>
			<%= book.title %> 
			<% if book.check_out %>
				<span class="label label-warning">Rented</span>
			<% end %>				
		</h2> 

		<p><b>Author:</b>	<%= book.author %></p>
		<p><b>Caregory:</b> <%= book.category %></p>
		
	<% end %>
<% end %>
</div>
<%= paginate @books %>


<% content_for :right_pane do %>

	<div class="filters">
	<h2> Filters:</h2>
		<%= form_with url: books_path, method: :get do |form| %>
		  <div class="input-group">
			  <span class="input-group-addon"><%= form.label :author, "By author:" %></span>
			  <%= form.text_field :author, class:"form-control" %>
		  </div>

		  <div class="input-group">
			  <span class="input-group-addon"><%= form.label :category, "By category:" %></span>
			  <%= form.text_field :category, class:"form-control" %> 
		  </div>

		  <h3>Filter by availability:</h3>
		  <div class="input-group">
			  <span class="input-group-addon"><%= form.radio_button :status, "false" %> </span>
			  <%= form.label :status, "Available to rent", class:"form-control" %> 
		  </div>
		  <div class="input-group">
			  <span class="input-group-addon"><%= form.radio_button :status, "true" %></span>
			  <%= form.label :status, "Rented", class:"form-control" %> 
		  </div>
	  	<%= form.submit "Filter", class:"btn" %>
	   <% end %>
	</div>

	<%= button_to "Add new book", new_book_path, method: :get if current_user.admin?%>
<% end %>

app/views/books/new.html.erb
<h1>Adding a new book</h1>
<%= render 'form' %>

<% content_for :right_pane do %>
  <%= button_to "Back", books_path, class: "btn" , method: :get%>
<% end %>

app/views/books/show.html.erb
<div class="title-show">
	<h1><%= @book.title %></h1>
	<div>
		<% unless @book.check_out %>
			<span class="label label-success">Available</span>
		<% else %>
			<span class="label label-danger">Unavailable</span>
		<% end %>		
	</div>
</div>

<div>
	<p><b>Author:</b> <%= @book.author %></p>
	<p><b>Category:</b> <%= @book.category %></p>
</div>

<% content_for :right_pane do %>
	<% if current_user.admin? %>
		<%= button_to "Edit book", edit_book_path(@book), method: :get %>
		<%= button_to "Delete book", book_path(@book), method: :delete %>
		<%= button_to "Take out this book", new_rental_path(@book), method: :get unless @book.check_out%>
	<% end %>

	<% unless current_user.admin? %>
		<%= button_to "Take out this book", rentals_path(:rental => {:book_id => @book.id, :user_id => current_user.id}), method: :post unless @book.check_out %>
	<% end %>
	<%= button_to "Back", books_path, method: :get %>
<% end %>