config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :books, :rentals
  devise_for :users, controllers: {sessions: 'users/sessions'}, :path_prefix => 'my'
  resources :users
  get 'static/home'

  root 'static#home'
end

app/views/layouts/_admin_links.html.erb
<%= link_to "Add User", new_user_path %>
<%= link_to "Add Book", new_book_path %>
<%= link_to "New Rental", new_rental_path %>

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_links.html.erb
<%= link_to 'My Rentals', rentals_path %>

app/views/layouts/_search.html.erb
<%= form_with url: books_path, method: :get do |form| %>
  <div class="input-group">
	  	<%= form.text_field :title, class:"form-control search", placeholder: "Search" %>
	  <span class="input-group-btn" aria-hidden="true">
	  	<%= button_tag(name: 'commit', type: 'submit', class: "btn btn-default") do %>
	  		<span class="glyphicon glyphicon-search" aria-hidden="true"></span>
	  	<% end %>	
  	  </span>
  </div>
  	
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>library_sys</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />

  </head>

  <body>


    <div class="navbar">
      <div class="navbar-center-cont">
        <div class="left-align">
          <%= link_to(root_path) do %>
            <h1>library_sys</h1>
          <% end %>
            <%= link_to "Books", books_path %>
          <% if user_signed_in? and current_user.admin? %>
            <%= render 'layouts/admin_links' %>
          <% elsif user_signed_in? %>  
            <%= render 'layouts/links' %>
          <% end %>
          <%= render 'layouts/search' %>
        </div>
        <div class="right-align">
          <% if user_signed_in? %>
            <%= button_to current_user.email, user_path(current_user), class:"btn", method: :get%>
            <%= button_to 'Sign-out', destroy_user_session_path, class:"btn", role:"group", method: :delete%>

          <% end %>
        </div>
      </div>
    </div>
    
    <div class="main-cont">
      <div><%= notice %></div>
      <div><%= alert %></div>

      <div class="center-cont">
        
        <div class="left-pane">
          <%= yield %>
        </div>

        <div class="right-pane">
          <%= yield :right_pane %>
        </div>
      </div>
      
    </div>
  </body>
</html>